### ISSUE TITLE
Pod Installation

### ISSUE THREAD

**Issue by moumitachina** [brightcove/brightcove-player-sdk-ios-googlecast#1]
Every time I try to install the sdk through cocoapods am getting this error even after doing "pod repo update" it's not installing, please have a look at this.
![Screenshot 2019-10-14 at 3 38 32 PM](https://user-images.githubusercontent.com/26344519/66743934-bd4eab80-ee98-11e9-8e84-55e359819a79.png)

**Comment by timothyrodgers** [comment]
Moumitachina,

In the future, please post questions to the [Brightcove Native Player SDKs developer forum](https://groups.google.com/forum/#!forum/brightcove-native-player-sdks) in Google Groups.

I have run `pod install` for both the objc and swift sample projects in ios-player-samples/GoogleCast/BasicCastPlayer which I fetched from https://github.com/BrightcoveOS/ios-player-samples and both installed successfully.

Please make sure you are running a recent version of CocoaPods (`gem install cocoapods`) and it might be necessary to completely clear your CocoaPods caches (`pod cache clean --all` and `pod repo update`).

If you still run into problems, please follow up in the developer forum.

IHTH,
Tim
